model:
  geometry:
    name: volume-volsdf
    grad_type: analytic
    center: [0, -0.3, 0]
    scale: [2.5, 2.5, 2.5]
    feature_dim: 16
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 17
      base_resolution: 16
      per_level_scale: 1.447269237440378
      include_xyz: true
      interpolation: Linear
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
    density:
      params_init: {beta: 0.3}
      beta_min: 0.0001