dataset:
  name: peoplesnapshot
  subject: female-4-casual
  gender: female
  dataroot: ../data/PeopleSnapshot/${dataset.subject}/
  train:
    num_workers: 8
    batch_size: 4
    start: 0
    end: 335
    skip: 4
    downscale: 2
    fitting: ${model.smpl.optimize_smpl}
    refine: ${model.smpl.refine_smpl}
  val:
    num_workers: 1
    batch_size: 1
    start: 335
    end: 335
    skip: 4
    downscale: 2
  test:
    num_workers: 4
    batch_size: 1
    start: 335
    end: 523
    skip: 4
    downscale: 2