dataset:
  name: peoplesnapshot
  subject: male-3-casual
  gender: male
  dataroot: ../data/PeopleSnapshot/${dataset.subject}/
  canonical_pose: ${model.deformer.canonical_pose}
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 455
    skip: 4
    downscale: 2
    fitting: ${model.smpl.optimize_smpl}
    refine: ${model.smpl.refine_smpl}
    canonical_pose: ${dataset.canonical_pose}
    gender: ${dataset.gender}
  val:
    num_workers: 8
    batch_size: 1
    start: 456
    end: 456
    skip: 4
    downscale: 2
    canonical_pose: ${dataset.canonical_pose}
    gender: ${dataset.gender}
  test:
    num_workers: 8
    batch_size: 1
    start: 456
    end: 675
    skip: 4
    downscale: 2
    canonical_pose: ${dataset.canonical_pose}
    gender: ${dataset.gender}